
'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google';
import toast, { Toaster } from 'react-hot-toast';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'


import "./globals.css";
import { QueryClientProvider , QueryClient } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient} >
        <GoogleOAuthProvider clientId="623391499930-c4utcukq2c320ghhek8dds5th6vne5re.apps.googleusercontent.com">
        {children}
        </GoogleOAuthProvider>
        <Toaster/>
        <ReactQueryDevtools/>
        </QueryClientProvider>
        </body>
    </html>
  );
}
